apiVersion: v1
kind: Service
metadata:
  name: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_SLUG__
  labels:
    app: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_SLUG__
spec:
  ports:
  - name: http
    port: 8880
    protocol: TCP
    targetPort: 8880
  selector:
    app: __CI_PROJECT_NAME__-__CI_ENVIRONMENT_SLUG__
  type: ClusterIP
